### PR TITLE
added portable lms

### PR DESCRIPTION
**Pull request by gbanegas**
- removed some printf from the middle of the code
- added fips202.h for the hash
- added api.h for calling the functions
- fixed the makefile for compiling arm-none-eabi-gcc

### CODE REVIEW

**Comment by sfluhrer** [comment]
Hmmmm, what's the reason for fips202.h; LMS doesn't use SHA-3 or SHAKE...

**Comment by gbanegas** [comment]
Sorry.. Wrong repo.

**Comment by sfluhrer** [comment]
Actually, there are some nonstandard parameter sets which do use SHAKE-256; I forgot about them (even though I'm an author of the draft...)

**Comment by gbanegas** [comment]
Yes, I am using some of the parameters and idea from https://eprint.iacr.org/2020/470 which has the focus in Cortex-M4. Sorry, I mix up the pull requests.

**Pull request closed without merging**
